config/routes.rb
Rails.application.routes.draw do

  root "stories#index"
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :stories do
    resources :votes
  end

  

  

end

app/models/story.rb
require 'pismo'
require 'link_thumbnailer'

class Story < ActiveRecord::Base
  belongs_to :user
  has_many :votes


  def points
    votes.upvotes.count - votes.downvotes.count
  end

  def self.page_preview(url)
    doc = Pismo::Document.new(url)
    page = {title: doc.title, opening: doc.body}
  end

  def self.page_image(url)
    doc = LinkThumbnailer.generate(url)
    image = { image: doc.image }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :stories
  has_many :votes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable

  def self.twitter_auth(response)
    credentials = { uid: response[:uid], provider: :twitter}
    pwd = Devise.friendly_token[0,20]

    User.find_or_create_by(credentials) do |user| 
      user.name = response[:info][:name]
      user.password = pwd
      user.password_confirmation = pwd
    end
  end

  def email_required?
    return false if provider == "twitter"
    super
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :story
  belongs_to :user
  scope :upvotes, -> { where(up: true) }
  scope :downvotes, -> { where(up: false) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def twitter
    user = User.twitter_auth(request.env["omniauth.auth"])
    sign_in_and_redirect user
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  before_action :authenticate_user!, except: [:index]
  def new
    @story = Story.new
  end

  def create
    @story = Story.new params[:story].permit(:link)
    @story.user = current_user
    info = Story.page_preview(@story.link)
    @story.title = info[:title]
    @story.opening = info[:opening]
    image_info = Story.page_image(@story.link)
    @story.image = image_info[:image]

    if @story.save
      redirect_to stories_path
    else
      render 'new'
    end
  end

  def index
    @stories = Story.all
  end

  def edit
    @story = Story.find params[:id]
  end

  def update
    @story = Story.find params[:id]
    @story.update params[:story].permit(:title, :link)
    redirect_to '/stories'
  end

  def destroy
    @story = Story.find params[:id]
    @story.delete
    redirect_to '/stories'
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    @story = Story.find(params[:story_id])
    Vote.create(up: params[:up], story: @story, user: current_user)

    WebsocketRails[:votes].trigger 'update_vote', { id: @story.id, points: @story.points }

    redirect_to '/stories'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Reddish" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </head>
  <body>

  <nav class="navbar navbar-inverse" role="navigation">
    <ul class="nav navbar-nav">
      <a class="navbar-brand" href="#">Reddish</a>
        <!-- <div class="rhs_nav"> -->
          <% if user_signed_in? %>
            <li>
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
            </li>
            <li>
              <%= link_to('Manage Your Account', edit_user_registration_path) %>
            </li>
          <% else %>
            <li>
              <%= link_to('Login', new_user_session_path)  %>  
            </li>
            <li>
              <%= link_to('Register', new_user_registration_path)  %>
            </li>
          <%end%>
          <li>
            <%= link_to 'Add a story', new_story_path, class: "btn btn-primary add-a-story" %>
          </li>
        <!-- </div> -->
    </ul>
  </nav>
    

    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Reddish 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/old_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddish</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= notice %>
<%= alert %>
<%= yield %>

</body>
</html>

app/views/stories/_form.html.erb
<%= form_for @story do |form| %>
 
  <%= form.label :link %>
  <%= form.text_field :link %>
  
  <%= form.button 'Submit' %>
<%end%>

app/views/stories/edit.html.erb
<%= render 'form' %>

app/views/stories/index.html.erb
<h1>
Reddish
</h1>
  <div class="story-container"> 
    <% @stories.each do |story| %>
      <div class="stories">
        <div class="row story_blocks">
          <div class="col-md-3 image_div">
          <img src=<%= story.image %> class="img-rounded preview_thumb">
          </div>
          <div class="col-md-7 story_text">
          <h2><a href='<%= story.link %>' target='_blank'><%=story.title.truncate(78) %></a></h2>
          <p><%= story.opening.truncate(380, omission: '... (continued)') %></p>
          </div>
          <div class="col-md-2">
            <div class="row rating">
              <div class="col-md-6 rating_text">
                <h4>Rating:</h4>
              </div>
              <div class="col-md-6 rating_number">
              <h4 class='votes_count' data-id='<%= story.id %>'><%= story.points %></h4>
              </div>
            </div>
            <div class="row">
              <%= button_to 'Upvote', story_votes_path(story, up: true), remote: true, class: "btn btn-success btn-block" %>
              <p></p>
              <%= button_to 'Downvote', story_votes_path(story, up: false), remote: true, class: "btn btn-danger btn-block" %>  
              <p><%= story.user %></p>
              <%= link_to 'Edit story', edit_story_path(story) %>
              <% if user_signed_in? && story.user_id == current_user.id %>
              <%= link_to 'Delete', story_path(story), method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<br>
<div class="container">
  <div class="row">
    <div class="col-md-12 add_a_story_footer">
      <%= link_to 'Add a story', new_story_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>
<footer>
</footer>

app/views/stories/new.html.erb
<%= render 'form' %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>